project:
  type: website
  output-dir: _site
  resources:
    - images/**
resource-path:
  - images
  - .

website:
  title: "Advanced GIS & RS"
  site-url: https://gisma-courses.github.io/LV-19-d19-006-25
  repo-url: https://github.com/gisam-courses/LV-19-d19-006-25
  repo-actions: []   # [source, issue, edit] bei Bedarf manuell setzen
  page-navigation: true
  bread-crumbs: false
  open-graph: true
  image: images/banner.png
  page-footer:
    center: |
      gisma spatial science ressources (<span class="year"></span>) —
      <a class="impressum-link" href="base/impressum.html">Impressum</a>

  search:
    location: navbar
    type: textbox

  navbar:
    background: primary
    foreground: light
    logo: images/logo.png
    left:
      - icon: question-square-fill
        text: FAQ
        href: base/faq.qmd
    right:
      - icon: chat-left-text-fill
        text: "ILIAS"
        href: "https://ilias.uni-marburg.de/ilias.php?baseClass=ilrepositorygui&ref_id=4407827"

  sidebar:
    pinned: true
    align: center
    style: docked
    contents: auto
    # collapse-level: 1
    # contents:
    #   - section: "Willkommen"
    #     contents:
    #       - index.qmd
    #       - base/about.qmd
    #   - text: "---"
    #   - section: "Kurs-Sitzungen"
    #     contents:
    #       - section: "Sitzung 1"
    #         contents:
    #           - session-1/sitzung-1-01.qmd
    #       - section: "Sitzung 2"
    #         contents:
    #           - session-2/sitzung-2-01.qmd
    #           - session-2/sitzung-2-02.qmd

format:
  html:
    theme:
      light: [lumen, css/custom.scss]

    css: css/styles.css
    toc: true
    code-copy: true
    code-background: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)//(gisma\-courses\.github\.io/LV\-19\-d19\-006\-25|www\.quarto\.org/custom)'
    md-extensions: +fenced_divs+bracketed_spans+link_attributes
    include-after-body:
      - "includes/_footer-year.html"


lang: de
