project:
  type: website
  output-dir: _site
  resources:
    - images/**
resource-path:
  - images
  - .

website:
  title: "Advanced GIS & RS"
  site-url: https://gisma-courses.github.io/LV-19-d19-006-25
  repo-url: https://github.com/gisma-courses/LV-19-d19-006-25
  repo-actions: []   # [source, issue, edit] bei Bedarf manuell setzen
  page-navigation: true
  bread-crumbs: false
  open-graph: true
  image: images/banner.png
  page-footer:
    center: |
      gisma spatial science ressources (<span class="year"></span>) —
      <a class="impressum-link" href="base/impressum.html">Impressum</a>

  search:
    location: navbar
    type: textbox

  navbar:
    background: primary
    foreground: light
    logo: images/logo.png
    left:
      - icon: question-square-fill
        text: FAQ
        href: base/faq.qmd
    right:
      - icon: chat-left-text-fill
        text: "ILIAS"
        href: "https://ilias.uni-marburg.de/ilias.php?baseClass=ilrepositorygui&ref_id=4407827"

  sidebar:
    pinned: true
    align: center
    style: docked
    contents:
      - section: "GIS Basics"
        contents:
          - href: https://gisma--courses-github-io.translate.goog/geoinfo-basis-qgis//unit01/unit01-01_reader_geo_raum.html?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp
            text: Space needs a scope
          - href: https://gisma--courses-github-io.translate.goog/geoinfo-basis-qgis//unit02/unit02-01_reader_gi_raum.html?_x_tr_sl=de&_x_tr_tl=en&_x_tr_hl=de&_x_tr_pto=wapp
            text: Spatial Representation in GI

      - text: "---"
      - section: "R-Spatial Basics"
        contents:
          - href: https://gisma-courses.github.io/LV-19-d19-006/morea/geocomputation-with-r/reading-screencast-spatial-r-gis-2.html
            text: Some Pros & Cons for R-Spatial
          - href: https://thinking-spatial.org/courses/geoinformationen_kommunizieren/kurs1/
            text: First steps in geospatial R (German Ressource)
          - href: https://r.geocompx.org/intro.html
            text: Geocomputation with R

      - text: "---"
      - section: "Lectures"
        contents:
          - href: reader/cd-1.qmd
            text: Spatial data classification
          - href: reader/mc3.qmd
            text: Filling Gaps
          - href: reader/cd2.qmd
            text: Data retrieval
          - href: slides/slides_session1.qmd
            text: Spatial Pattern Description
          - href: slides/slides_session2.qmd
            text: Landscape Patterns
          - href: slides/slides_session3.qmd
            text: Landscape Patterns Reloaded
          - href: slides/slides_session4.qmd
            text: Pattern-based spatial analysis
          - href: slides/slides_session5.qmd
            text: Continous data spatial analysis

      - text: "---"
      - section: "Worksheets"
        contents:
          - worksheets/comingsoon.qmd
          - worksheets/comingsoon.qmd
          - worksheets/comingsoon.qmd
          - worksheets/comingsoon.qmd
          - worksheets/comingsoon.qmd
          - worksheets/comingsoon.qmd

format:
  html:
    theme:
      light: [lumen, css/custom.scss]
    css: css/styles.css
    toc: true
    code-copy: true
    code-background: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)//(gisma\-courses\.github\.io/LV\-19\-d19\-006\-25|www\.quarto\.org/custom)'
    md-extensions: +fenced_divs+bracketed_spans+link_attributes
    include-after-body:
      - includes/_footer-year.html

lang: de
