---
title: Data retrieval with R 
#author: Chris Reudenbach
#date: '2024-12-06'
title-block-banner: images/hinterland-sp.jpg
title-block-banner-color: green
editor: 
  markdown: 
    wrap: sentence
---



Access to spatial and spatio-temporal data sets, which are available in ever greater quantities and quality, is an essential basic task of any spatial or descriptive data analysis in the geosciences and related fields. An ever-growing number of websites, R packages and tutorials support this data access and thus lower a significant barrier to entry.

Below you will find a preliminary and unorganized list of links that provide access to packages, data and tutorials. Most of the links lead directly to the corresponding example code.

* Common approaches
   * [rspatialdata](https://rspatialdata.github.io/) from Paula Moraga and Laurie Baker is a extremely useful collection of data sources and tutorials on downloading and visualising spatial data using R.
   * [packages to download open spatial data](https://www.paulamoraga.com/book-spatial/r-packages-to-download-open-spatial-data.html) Same author as before very brief and effective introduction to this topic
   * [acesss to reanalysis](https://dominicroye.github.io/en/2018/access-to-climate-reanalysis-data-from-r/)
* Specific packages
  * [easyclimate](https://verughub.github.io/easyclimate/)
  * [online weather data](https://r4photobiology.info/galleries/online-weather-data.html)
  * [climate4R](https://github.com/SantanderMetGroup/climate4R)
  * [cstools](https://cran.r-project.org/web/packages/CSTools/index.html))
  * [naturalearthdata](https://docs.ropensci.org/rnaturalearthdata/)
  * [soilDB](https://ncss-tech.github.io/soilDB/)
  * [geodata](https://cran.r-project.org/web/packages/geodata/index.html)
  * [rdwd](https://bookdown.org/brry/rdwd/) DWD data access
* Data providers
  * [cmsaf](https://www.cmsaf.eu/EN/Products/Tools/R/R_node.html)
  * [ropensci](https://ropensci.org/packages/data-access/)
  * [openeo](https://openeo.org/documentation/1.0/r/#full-example)
  
* Tutorials  
   * [pRecipe](https://cran.r-project.org/web/packages/pRecipe/vignettes/case_study.html)
   * [Earth System Science Course](https://pjbartlein.github.io/REarthSysSci/overview.html)
   * [dealing with netCDF](https://pjbartlein.github.io/REarthSysSci/netCDF.html)

```{r geometries}
#| eval: true
#| echo: true
#| warning: false
#| message: false

```



## Final Remarks


